petoju/terraform-provider-mysql

mysql/resource_grant.go, mysql/resource_grant_test.go, website/docs/r/grant.html.markdown
It wasn't implemented correctly and import needed more runs of apply
before it worked correctly in some cases.
We should eventually write tests and documentation for this...
=> Provide a way to import user/host/database/table grant in one go

mysql/provider.go, mysql/resource_database.go, mysql/resource_grant.go, mysql/resource_grant_test.go, mysql/resource_user.go, mysql/resource_user_password.go, mysql/resource_user_test.go, website/docs/r/user.html.markdown
This is mostly for some imports / unification.
This is the first PoC, it needs docs changes + tests.
=> Add support to specify hashed password

website/docs/r/ti_config.html.markdown
This commit will add missing documentation for `mysql_ti_config`
=> Add missing documentation for mysql_ti_config

GNUmakefile, scripts/tidb-test-cluster.sh
* use isolated docker network instead of magic with MYIP
* init script can accept TiDB version
* minor changes in usage help
=> Improve script for TiDB tests

mysql/resource_global_variable.go, mysql/resource_global_variable_test.go
This commit will fix value string, integer, float and boolean parsing issues and closes issue #22
=> Value string, integer, float and boolean parsing issues fix

mysql/data_source_tables.go, mysql/resource_database.go, mysql/resource_global_variable.go, mysql/resource_grant.go, mysql/resource_grant_test.go, mysql/resource_role.go, mysql/resource_sql.go, mysql/resource_ti_config_variable.go, mysql/resource_user.go, mysql/resource_user_password.go, mysql/utils.go
The idea is to provide users with ability to cancel any operation.
=> Add context-aware functions

website/docs/r/user_password.html.markdown
It is no longer in code and the docs say it's required
=> Remove pgp_key

mysql/resource_user.go
This is only a quick fix, it will need tests later
=> Fix applying changes of passwords

.circleci/config.yml, GNUmakefile, mysql/provider.go
=> Fix compatibility with MariaDB 10.10

mysql/resource_user.go
Fixes https://github.com/petoju/terraform-provider-mysql/issues/79
=> Support older version of aad_auth

website/docs/r/database.html.markdown
https://github.com/petoju/terraform-provider-mysql/pull/8
=> Update default value

mysql/resource_grant.go, mysql/resource_grant_test.go
Based on https://github.com/petoju/terraform-provider-mysql/issues/89
=> Fix granting roles with admin option

mysql/resource_grant.go, mysql/resource_grant_test.go
We need more time to debug the list of commits changing how grants work.
=> Revert "Fix GRANT OPTION"

mysql/provider.go
Enable IAM logging for Cloud SQL DBs instead of using username/password
=> Adding options to enable IAM database AuthN in Cloud SQL

mysql/resource_grant.go, mysql/resource_grant_test.go, mysql/utils.go
This PR fixes two bugs I noticed related to resource grant conflicts:
1. It is currently impossible to create multiple grants for the same user for different tables, because the ids conflict. This fixes the IDs to include the table or procedure name.
2.  If you try to create multiple conflicting resource grants, this may or may not be caught by the conflict detection logic because MySQL requests can be issued in parallel. This introduces a keyed mutex around grant creation and deletion to ensure that conflicts are caught.
Added unit tests
=> fix: bugs in resource grant conflicts

mysql/resource_grant.go, mysql/resource_grant_test.go
- This fixes #120. See description in #120.
- See inline comments.
- Adds unit tests.
=> Fix ALL + GRANT Bug (#120)

GNUmakefile, mysql/resource_database_test.go, mysql/resource_grant.go, mysql/resource_grant_test.go
Recent refactoring caused some issues after setting database/table was removed.
Adding it there fixes the issues
=> Fix grant import

mysql/resource_grant.go, mysql/resource_grant_test.go
This was forgotten on refactoring. Also, tests was changed to catch this issue.
=> Escape granted role names

mysql/data_source_databases.go, mysql/data_source_databases_test.go, mysql/provider.go, website/docs/d/databases.html.markdown, website/mysql.erb
I'd like to get a list of databases from the MySQL server like `mysql_tables` data source, so I implemented it.
=> mysql_databases Data source

website/docs/r/grant.html.markdown
=> Update `resource_grant` import description

mysql/resource_grant.go, mysql/resource_grant_test.go
=> chore: remove unused code

mysql/resource_grant.go, mysql/resource_grant_test.go, website/docs/r/grant.html.markdown
=> Make database optional in grant resource

website/docs/r/user_password.html.markdown
related with https://github.com/petoju/terraform-provider-mysql/pull/41
=> Remove PGP key description

GNUmakefile, mysql/resource_grant_test.go, scripts/changelog-links.sh, scripts/gogetcookie.sh
- Added support for MySQL 8.4.5 in tests; 
- Added an explicit test case or the privileges addition; 
- Increased version of Terraform to 1.11.3.
=> Added support for MySQL 8.4.5 in tests; added an explicit test case or the privileges addition; used 1.11.3 of Terraform
