petoju/terraform-provider-mysql

mysql/resource_database.go
mysql/resource_database_test.go

MySQL 8.0.28 starts handling utf8 differently, that may lead to
persistent diff.
I am not convinced this is the best solution, but I am not convinced I
should do something else.

Fix tests with MySQL 8.0.28 (fixes #7)

---

.gitignore
GNUmakefile
mysql/provider.go
mysql/provider_test.go
mysql/resource_database_test.go
mysql/resource_global_variable.go
mysql/resource_global_variable_test.go
mysql/resource_grant_test.go
mysql/resource_user_test.go
website/docs/r/global_variable.html.markdown

To have state for MySQL global configuration with IaC I'd like to introduce new resource: mysql_global_variable

New resource: mysql_global_variable

---

mysql/resource_grant.go

That removes SSL requirements from the user, so let's be careful about
that.
As none is the default, we'll skip it here.

Explicitly skip tls_option=none for grants

---

website/docs/d/tables.html.markdown
website/mysql.erb

Because tabels is implemented but not documented.

Add data.tables documentation

---

website/docs/r/user.html.markdown

mysql_user can be imported, but it was not documented.

Add documentation for import mysql_user resource

---

mysql/resource_grant.go

Also improve grant debuggability by printing them out

Ignore double quotes in grants

---

mysql/provider_test.go

We did not check the errors before, but that makes testing more difficult.
I am also removing sql_log_bin = 0; we don't strictly need it for testing and there is a reason why some DBs (like RDS) don't allow it.

Remove sql_log_bin in tests, add Fatals on errors

---

mysql/resource_rds_config.go
mysql/resource_rds_config_test.go

The else only works if there is a row in the config. 
But if there is no existing value set it is a empty string and it can not convert to integer. 
`Error: failed reading target delay in RDS config: strconv.Atoi: parsing "": invalid syntax`

fix: strconv.Atoi: strconv.Atoi: parsing "": invalid syntax

---

mysql/resource_user.go
website/docs/r/user.html.markdown

Supports creating users authorized by AzureAD tokens instead of passwords https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-azure-ad-authentication
Although aad_auth is MySQL plugin and there is theoretical possibility to use `CREATE USER ... IDENTIFIED WITH 'aad_auth' AS 'AADUser:objectid:upn:objectname' `, this is currently not documented solution. As aad_auth is in public preview only, there is no guarantee this command would work.
Therefore I tried to follow documentation and implement Microsoft specific `CREATE AADUSER` command as much as possible complying with documentation.
What this PR can do:
```
resource mysql_user {
user = "someuser" # name used to login to MySQL - in Microsoft's documentation it's alias (CREATE AADUSER x AS alias)
auth_plugin = "aad_auth" …
```

Add support for CREATE AADUSER to mysql_user resource

---

mysql/provider.go
mysql/provider_test.go
mysql/resource_grant.go
mysql/resource_grant_test.go
website/docs/r/grant.html.markdown

It seems dynamic grants in MySQL8 don't obey the original grant model, where SHOW GRANTS shows them in 1 row.
Instead, there are 2 rows - one for static grants like SELECT and one for dynamic grants.
I added test and started merging all grants to make sure we get everything here.
As the new test works now (and didn't work before), I am reasonably convinced this works.

Support dynamic grants in MySQL8

---

mysql/resource_grant.go

Refactoring caused us to handle some cases of procedure/function grants incorrectly. This PR is a quick fix to that.

Incorrect grant parsing fix

---

mysql/provider.go
mysql/provider_test.go
mysql/resource_grant_test.go
mysql/resource_user.go
mysql/resource_user_password.go
mysql/resource_user_test.go
website/docs/r/user.html.markdown

Hello :wave:, this PR introduce the possibility of retaining the old password when the password change as described in https://github.com/petoju/terraform-provider-mysql/issues/17.
I would like to add a test but I'm not very fluent in Go and unless I'm mistaken there are currently no test that check if the user password works from which I could copy/inspire. Any feedback or advice is very welcome :pray:

feat: add retain old password support

---

GNUmakefile
mysql/resource_grant.go
mysql/resource_grant_test.go

- The `resource_grant` resource is very convoluted. For instance, the database might not be a database, and the table might not be a table (e.g. https://github.com/petoju/terraform-provider-mysql/pull/98/files#r1451607847). 
- To fix this, I introduced various structs, which makes the logic for parsing grants much easier to read.
- I additionally added first-class support for procedure grants (https://github.com/petoju/terraform-provider-mysql/issues/99).
- This sets the stage for subsequent PRs to actually create separate Terraform resources for each of these things, which would make the logic far easier to manage.

Schematize resource_grant

---

mysql/resource_grant.go
mysql/resource_grant_test.go

- Per [comment here](https://github.com/petoju/terraform-provider-mysql/issues/99#issuecomment-1906679395) adds a regression test for "Example 2" way of defining procedures, and fixes the behavior.

breakfix: Fix Example 2 of Procedure Loading, reading state for non-deleted grants

---

go.mod
mysql/provider.go
website/docs/index.html.markdown

* Add `iam_database_authentication` option in the provider to switch on/off IAM authN
* If `iam_database_authentication`, the `password` field will be a temporary access token. The implementation follows the example made in [the documentation](https://cloud.google.com/sql/docs/mysql/iam-logins#log-in-with-automatic).

Enable automatic IAM database authN for Cloud SQL

---

GNUmakefile

Note that these are only temporary fixes - we should migrate website to MDX and people generally shouldn't use "make test" or we should protect it somehow.
This is to make development easier.

Fix "make test" and "make website"

---

mysql/provider.go
website/docs/index.html.markdown

GCP Cloud SQL - Add support for PRIVATE_IP #117 
Add new bool option private_ip to connect to gcp cloud sql instance with private ip without locally running cloud-sql-proxy

Add Cloud SQL instances private ip option

---

mysql/provider.go
website/docs/index.html.markdown

The current implementation for TLS requires that the certificates exist on disk - however, if the only access you have to these secrets is via an external secret manager (say SecretManager, Vault etc).
I did think of creating two new parameters but it felt like it was easier to discover if someone had used a string of a cert instead of a file path.

Add Ability to load Certificates from Data Resources/Secrets

---

mysql/provider.go

To support aad authentication in other Azure Clouds, the scope needs to be updated for the the destination Azure Cloud.
To support detection of which cloud is being used, the code references the Terraform azurerm provider environment variable [ARM_ENVIRONMENT](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#environment).
It is likely this URL could be grabbed from the Azure go SDK since it is available via the az CLI.
```
az cloud show --name AzureCloud |grep ossrdbms
"ossrdbmsResourceId": "https://ossrdbms-aad.database.windows.net",
az cloud show --name AzureChinaCloud |grep ossrdbms
"ossrdbmsResourceId": "https://ossrdbms-aad.database.chinacloudapi.cn",
az cloud show --name AzureUSGovernment |grep ossrdbms
"ossrdbmsResourceId": …
```

Add support for all Azure Clouds

---

mysql/provider.go
mysql/resource_default_roles.go
mysql/resource_default_roles_test.go
website/docs/r/default_roles.html.markdown

Closes #38 and #119.
This PR adds a new resource called `mysql_default_roles` which allows you to set default rolest to users using the [ALTER USER ... DEFAULT ROLE](https://dev.mysql.com/doc/refman/8.0/en/alter-user.html) syntax.
**Example:**
```hcl
resource "mysql_role" "readonly" {
name = "readonly"
}
resource "mysql_user" "jdoe" {
user = "jdoe"
host = "%"
}
resource "mysql_grant" "jdoe" {
user     = mysql_user.jdoe.user
host     = mysql_user.jdoe.host
database = ""
roles    = [mysql_role.readonly.name]
}
resource "mysql_default_roles" "jdoe" {
user  = mysql_user.jdoe.user
host  = mysql_user.jdoe.host
roles = mysql_grant.jdoe.roles
}
```
I also added tests for this new resource and created a documentation page.
@petoju What do you think? Could you look over this PR? And thank you for …

Add default roles resource

---

mysql/provider.go

Support ANSI_QUOTES default set on server

---

mysql/resource_database.go
mysql/resource_default_roles.go
mysql/resource_default_roles_test.go
mysql/resource_grant.go
mysql/resource_rds_config.go
mysql/resource_rds_config_test.go
mysql/resource_sql.go
mysql/resource_user.go
mysql/resource_user_password.go
mysql/resource_user_test.go

I added everywhere [DEBUG] as that is how it should be when logging for TF provider.
Also grant parsing gets more detailed logging to catch errors.

Change error strings, add details for grant parsing

---

mysql/provider.go
mysql/resource_user.go

This will slow down apply, but at least this will behave correctly everywhere.

Set max number of connections to 1

---

mysql/data_source_tables.go
mysql/data_source_tables_test.go
mysql/provider.go
mysql/provider_test.go
mysql/resource_database.go
mysql/resource_database_test.go
mysql/resource_default_roles_test.go
mysql/resource_global_variable.go
mysql/resource_global_variable_test.go
mysql/resource_grant.go
mysql/resource_grant_test.go
mysql/resource_rds_config.go
mysql/resource_rds_config_test.go
mysql/resource_role_test.go
mysql/resource_ti_config_variable.go
mysql/resource_ti_config_variable_test.go
mysql/resource_user.go
mysql/resource_user_password_test.go
mysql/resource_user_test.go
mysql/utils.go

This should change no functionality at all

Refactoring: remove deprecated function calls, use our functions

---

mysql/provider.go
website/docs/index.html.markdown

This pull request adds the `azure_config` provider configuration block which allows the user to pass Azure credentials and other configuration options.
This is useful when relying on the `DefaultAzureCredential` feature of the Azure SDK is not sufficient, such as when configuring multiple servers across multiple tenants from the same Terraform state.
```hcl
provider "mysql" {
endpoint = "azure://your-azure-instance-name.mysql.database.azure.com"
username = "username@yourtenant.onmicrosoft.com"
azure_config {
tenant_id     = "your-tenant-id"
client_id     = "your-client-id"
client_secret = var.client_secret
}
}
```
All variables are optional, falling back to their corresponding environment variables if absent. If the entire block is missing, the previous behaviour is preserved and …

Add Azure configuration block

---

mysql/resource_grant.go
mysql/resource_grant_test.go

New grant introduced in MySQL 8 `FIREWALL_EXEMPT` is detected as `ALL PRIVILEGES` due to the regex for detecting all privileges.
This change ensures that `ALL`, `ALLPRIVILEGES` or `ALL PRIVILEGES` is actually found in the list of grants and not other strings containing them.

Check for ALL PRIVILEGES with boundaries. Improve test case for MySQL 8

---

.circleci/config.yml
GNUmakefile
README.md
mysql/provider.go
mysql/provider_test.go
mysql/resource_database.go
mysql/resource_database_test.go
mysql/resource_default_roles_test.go
mysql/resource_grant_test.go
mysql/resource_user_test.go
scripts/tidb-test-cluster.sh

This patch looks up collation based on INFORMATION_SCHEMA.COLLATIONS and scopes the response to just the two required columns.
The intention is that it will be a more steady reference and interface because we're able to select only the required columns rather than breaking when new columns are added to the interface for `SHOW COLLATION...`.
Context: using this provider broke for v7.5 of TiDB but I think there's a more durable approach by looking up directly the columns needed (more below).
This patch uses that `INFORMATION_SCHEMA.COLLATIONS` lookup to be compatible with the following:
1. Mysql 5.7 and 8.0 without special casing
2. MariaDB without special casing (assumed base on prior compatibility)
3. compatible with TiDB for 6.x and 7.x (v7.5.1 which advertises as 8.0.11-TiDB-v7.5.1 but …

Change collation lookup to be durable across additional engine/versions

---

mysql/resource_user_password.go

Currently, the password is printed out in apply/plan even when rotated.
The attribute can't be set to sensitive, and if using Atlantis, the existing password will appear in PRs where it is automated. 
if apply fails, it means that the active password was exposed
**How to reproduce**
```hcl
terraform {
required_version = "~> 1.0"
required_providers {
mysql = {
source  = "petoju/mysql"
version = "3.0.62"
}
}
}
resource "mysql_user" "app_user" {
user        = "test_user"
host        = "%"
tls_option  = "SSL"
auth_plugin = "caching_sha2_password"
}
resource "mysql_user_password" "app_user_password" {
user = mysql_user.app_user.user
host = mysql_user.app_user.host
}
output "plaintext_password" {
sensitive = true
value     = mysql_user_password.app_user_password.plaintext_password
}
```
**Then …

Fix: hide mysql_user_password.cleartext_password in plan/apply output

---

mysql/resource_grant.go

We forgot about one case - this was changed so it works in such cases.
Tests will come later.

Fix finding grant conflicts for EXECUTE grants

---

mysql/resource_grant.go
mysql/resource_grant_test.go

Fix for https://github.com/petoju/terraform-provider-mysql/issues/169#issuecomment-2581493599. Tested locally and confirmed that the roles are granted successfully and the state inconsistency is resolved!

fix: ignore host when comparing role grants

---

README.md

docs: update README rationale – note `winebarrel/terraform-provider-mysql` repository is archived since Oct 11, 2022 (making pull requests pointless) and apply grammar fixes for improved clarity.

docs: update README rationale

---

.goreleaser.yml

GoReleaser v2.8.2 gave 'error only version: 2 configuration files are supported, yours is version: 0, please update your configuration' unless the version was explicitly specified in the YAML file. 
Without adding `version: 2` to the YAML file, you could not compile the terraform-provider-mysql

Fixed the GoReleaser error "only version 2 configuration files are supported"

---

mysql/provider.go

This document describes the implementation of HTTP/HTTPS proxy support in the MySQL Terraform provider.
The MySQL provider has been updated to support HTTP and HTTPS proxies in addition to the existing SOCKS proxy support. This enhancement allows users to connect to MySQL databases through corporate proxies that use HTTP/HTTPS protocols.
1. **Proxy URL Validation**:
- The provider now accepts proxy URLs with `http://` and `https://` schemes
- The validation regex has been updated to include these schemes: `^(socks5h?|http|https)://.*:\d+$`
2. **Proxy Dialer Implementation**:
- The `makeDialer` function has been enhanced to handle HTTP/HTTPS proxy URLs
- When an HTTP/HTTPS proxy is detected, it logs the proxy type and uses the appropriate dialer
3. **Environment Variables**:
- The provider …

MySQL Provider HTTP/HTTPS Proxy Support

---

mysql/resource_user.go
mysql/resource_user_test.go
website/docs/r/user.html.markdown

feat: support for auth_string_hex

---

mysql/resource_grant.go
mysql/resource_grant_test.go

Reproduces https://github.com/petoju/terraform-provider-mysql/issues/246

feat: reproduced the uppercase grants of column names with reserved keywords
